---
- name: Manage GNS3 devices
  hosts: all
  gather_facts: false
  connection: ansible.netcommon.network_cli
 # Creates VLAN using loop instead of creating severals lines for each vlan or 3 differents tasks

  tasks:
    - name: Create new vlans
      cisco.ios.ios_vlans:
        config:
        - name: '{{ item.name }}'
          vlan_id: '{{ item.id }}'
          state: active
          shutdown: disabled
        state: merged

      loop:
        - id: 100
          name: IT-100
        - id: 300
          name: Accouting-300
        - id: 400
          name: Sales-4
