---
- name: Configure switches IosV
  hosts: sw-iosv
  gather_facts: false
 #connection: ansible.netcommon.network_cli

  tasks:
    - name: Assign VLAN to interfaces
      cisco.ios.ios_config:
        parents: interface range gig1/0-3
        lines:
          - switchport mode access
          - switchport access vlan 100

- name: Configure switch IOU
  hosts:  sw-iou
  gather_facts: false

  tasks:
    - name: configure interface
      cisco.ios.ios_config:
        parents: interface range ethernet1/0-3
        lines:  
          - switchport mode access
          - switchport access vlan 12

- name: VTP conf
  hosts:  all
  gather_facts: false

  tasks: 
    - name: configure interface
      cisco.ios.ios_config:
        lines:  
          - vtp domain CalBank
          - vtp mode client 
          - vtp password cisco

        