---

switches:
  hosts:
    sw-1:
      ansible_host: 192.168.122.100
    sw-2:
      ansible_host: 192.168.122.101
  vars:
    ansible_user: admin
    ansible_password: cisco
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable